apply plugin: 'com.android.library'

android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 34

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/services/javax.annotation.processing.Processor']
            pickFirsts += ['META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties', 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml', 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties', 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml']
        }
    }
    configurations{
        all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
    }
    namespace 'com.mytechia.robobo.framework.hri.vision'
    androidResources {
        noCompress 'lite'
    }
    lint {
        disable 'InvalidPackage'
    }

}

dependencies {
    /*
     * Please, avoid using nightly versions
     */
    //implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.mytechia:robobo-framework:1.3.4'
    implementation 'com.mytechia:robobo-remote-control:1.0.3-SNAPSHOT'
    implementation 'com.mytechia:robobo-remote-control-ws:1.0.2.1'

    implementation 'com.google.zxing:core:3.3.3'

    implementation ('com.mytechia:opencv:4.3.0.3-my-SNAPSHOT'){
        changing true
    }

    implementation 'com.google.code.gson:gson:2.10.1'


    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'

    //implementation files('../libs/opencv4_1_0_contrib-release.aar')

    implementation "androidx.annotation:annotation:1.0.0"


}



//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'
// apply plugin: "com.vanniktech.maven.publish"

/*
afterEvaluate { project ->
    android.libraryVariants.all { variant ->
        tasks.androidJavadocs.doFirst {
            classpath += files(variant.javaCompile.classpath.files)
        }
    }
}*/